replicaCount: 2

deployment:
  repository: kakaocloud-online.kr-central-2.kcr.dev/k8s-registry/demo-spring-boot
  tag: "9.0"
  pullSecret: regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  path: /
  sslRedirect: "false"

configMap:
  WELCOME_MESSAGE: "Welcome to Kakao Cloud"
  BACKGROUND_COLOR: "#4a69bd"

secret:
  DB1_PORT: '3306'
  DB1_URL: 'az-a.data2.3c598fbfdcb4453690aa1111f12f59f6.mysql.managed-service.kr-central-2.kakaocloud.com'
  DB1_ID: 'admin'
  DB1_PW: 'admin1234'
  DB2_PORT: '3307'
  DB2_URL: 'az-b.data2.3c598fbfdcb4453690aa1111f12f59f6.mysql.managed-service.kr-central-2.kakaocloud.com'
  DB2_ID: 'admin'
  DB2_PW: 'admin1234'

job:
  name: sql-job
  image: mysql:5.7
  scriptConfigMap: sql-script
  backoffLimit: 4

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  averageUtilization: 50

