apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB1_PORT: 'MzMwNg=='
  DB1_URL: 'YXotYS5kYXRhMi4zYzU5OGZiZmRjYjQ0NTM2OTBhYTExMTFmMTJmNTlmNi5teXNxbC5tYW5hZ2VkLXNlcnZpY2Uua3ItY2VudHJhbC0yLmtha2FvY2xvdWQuY29t'
  DB1_ID: 'YWRtaW4='
  DB1_PW: 'YWRtaW4xMjM0'
  DB2_PORT: 'MzMwNw=='
  DB2_URL: 'YXotYi5kYXRhMi4zYzU5OGZiZmRjYjQ0NTM2OTBhYTExMTFmMTJmNTlmNi5teXNxbC5tYW5hZ2VkLXNlcnZpY2Uua3ItY2VudHJhbC0yLmtha2FvY2xvdWQuY29t'
  DB2_ID: 'YWRtaW4='
  DB2_PW: 'YWRtaW4xMjM0'