#!/usr/bin/env python3
import json
import os
import shutil
import subprocess
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse
from urllib.request import Request, urlopen


APP_DIR = Path("/opt/cdn-lab")
CONFIG_PATH = Path("/etc/cdn-lab/config.json")
NGINX_CONF_PATH = Path("/etc/nginx/conf.d/cdn-lab.conf")
CACHE_DIR = Path("/var/cache/nginx/cdn-lab")
STATIC_DIR = APP_DIR / "static"

DEFAULT_CONFIG = {
    "origin_url": "",
    "ttl_seconds": 60,
    "cache_size": "100m",
    "inactive": "60m",
    "admin_port": 8080,
}


def run(command):
    completed = subprocess.run(command, text=True, capture_output=True)
    if completed.returncode != 0:
        raise RuntimeError((completed.stderr or completed.stdout).strip())
    return completed.stdout.strip()


def load_config():
    if not CONFIG_PATH.exists():
        return DEFAULT_CONFIG.copy()
    with CONFIG_PATH.open("r", encoding="utf-8") as file:
        data = json.load(file)
    config = DEFAULT_CONFIG.copy()
    config.update(data)
    return config


def save_config(config):
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with CONFIG_PATH.open("w", encoding="utf-8") as file:
        json.dump(config, file, ensure_ascii=False, indent=2)


def validate_size(value, field_name):
    value = str(value).strip().lower()
    if not value or len(value) > 12:
        raise ValueError(f"{field_name} 값이 올바르지 않습니다.")
    if value[-1] not in "kmg" or not value[:-1].isdigit():
        raise ValueError(f"{field_name}는 100m, 1g 같은 형식이어야 합니다.")
    return value


def validate_duration(value, field_name):
    value = str(value).strip().lower()
    if not value or len(value) > 12:
        raise ValueError(f"{field_name} 값이 올바르지 않습니다.")
    if value[-1] not in "smhd" or not value[:-1].isdigit():
        raise ValueError(f"{field_name}는 60s, 10m 같은 형식이어야 합니다.")
    return value


def validate_config(payload):
    origin_url = str(payload.get("origin_url", "")).strip().rstrip("/")
    parsed = urlparse(origin_url)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        raise ValueError("Origin URL은 http:// 또는 https://로 시작해야 합니다.")
    if parsed.username or parsed.password:
        raise ValueError("Origin URL에는 사용자명이나 비밀번호를 넣을 수 없습니다.")

    ttl_seconds = int(payload.get("ttl_seconds", DEFAULT_CONFIG["ttl_seconds"]))
    if ttl_seconds < 1 or ttl_seconds > 86400:
        raise ValueError("TTL은 1초부터 86400초 사이여야 합니다.")

    return {
        "origin_url": origin_url,
        "ttl_seconds": ttl_seconds,
        "cache_size": validate_size(payload.get("cache_size", "100m"), "Cache size"),
        "inactive": validate_duration(payload.get("inactive", "60m"), "Inactive"),
        "admin_port": int(payload.get("admin_port", DEFAULT_CONFIG["admin_port"])),
    }


def nginx_config(config):
    parsed = urlparse(config["origin_url"])
    host = parsed.netloc
    ttl = int(config["ttl_seconds"])
    cache_size = config["cache_size"]
    inactive = config["inactive"]
    origin_url = config["origin_url"].rstrip("/") + "/"

    return f"""# Managed by CDN Lab. Do not edit this file by hand.
proxy_cache_path {CACHE_DIR} levels=1:2 keys_zone=cdn_lab_cache:10m max_size={cache_size} inactive={inactive} use_temp_path=off;

server {{
    listen 80 default_server;
    server_name _;

    access_log /var/log/nginx/cdn-lab-access.log;
    error_log /var/log/nginx/cdn-lab-error.log;

    location = /__cdn_lab_health {{
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\\n";
    }}

    location / {{
        proxy_pass {origin_url};
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_set_header Host {host};
        proxy_set_header Connection "";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache cdn_lab_cache;
        proxy_cache_valid 200 206 {ttl}s;
        proxy_cache_valid 301 302 {ttl}s;
        proxy_cache_valid 404 30s;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;

        add_header X-Cache-Status $upstream_cache_status always;
        add_header X-CDN-Server "VM-CDN-Lab" always;
    }}
}}
"""


def apply_nginx_config(config):
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    NGINX_CONF_PATH.write_text(nginx_config(config), encoding="utf-8")
    run(["nginx", "-t"])
    run(["systemctl", "reload", "nginx"])


def nginx_status():
    try:
        run(["systemctl", "is-active", "--quiet", "nginx"])
        active = True
    except RuntimeError:
        active = False
    try:
        test_output = run(["nginx", "-t"])
        config_ok = True
    except RuntimeError as exc:
        test_output = str(exc)
        config_ok = False
    return {"active": active, "config_ok": config_ok, "nginx_test": test_output}


def purge_cache():
    cache_root = CACHE_DIR.resolve()
    if str(cache_root) != str(CACHE_DIR):
        raise RuntimeError("Cache 경로 확인에 실패했습니다.")
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    for item in CACHE_DIR.iterdir():
        if item.is_dir():
            shutil.rmtree(item)
        else:
            item.unlink()
    run(["systemctl", "reload", "nginx"])


def probe_cdn(path="/index.html"):
    if not path.startswith("/"):
        path = f"/{path}"
    if ".." in path:
        raise ValueError("확인할 경로가 올바르지 않습니다.")

    request = Request(f"http://127.0.0.1{path}", method="HEAD")
    started = time.perf_counter()
    with urlopen(request, timeout=15) as response:
        elapsed_ms = round((time.perf_counter() - started) * 1000, 2)
        headers = {key: value for key, value in response.headers.items()}
        return {
            "path": path,
            "status": response.status,
            "elapsed_ms": elapsed_ms,
            "cache_status": headers.get("X-Cache-Status", ""),
            "cdn_server": headers.get("X-CDN-Server", ""),
            "headers": headers,
        }


class Handler(BaseHTTPRequestHandler):
    server_version = "CDNLabAdmin/1.0"

    def log_message(self, fmt, *args):
        print("%s - %s" % (self.address_string(), fmt % args))

    def send_json(self, status, payload):
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def read_json(self):
        length = int(self.headers.get("Content-Length", "0"))
        if length > 1024 * 64:
            raise ValueError("요청 본문이 너무 큽니다.")
        body = self.rfile.read(length).decode("utf-8")
        return json.loads(body or "{}")

    def serve_static(self):
        path = self.path.split("?", 1)[0]
        if path == "/":
            path = "/index.html"
        target = (STATIC_DIR / path.lstrip("/")).resolve()
        if not str(target).startswith(str(STATIC_DIR.resolve())) or not target.exists():
            self.send_error(404)
            return
        content_type = "text/plain"
        if target.suffix == ".html":
            content_type = "text/html; charset=utf-8"
        elif target.suffix == ".css":
            content_type = "text/css; charset=utf-8"
        elif target.suffix == ".js":
            content_type = "application/javascript; charset=utf-8"
        body = target.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path.startswith("/api/status"):
            config = load_config()
            self.send_json(200, {"config": config, "nginx": nginx_status()})
            return
        self.serve_static()

    def do_POST(self):
        try:
            if self.path.startswith("/api/config"):
                config = validate_config(self.read_json())
                save_config(config)
                apply_nginx_config(config)
                self.send_json(200, {"ok": True, "config": config, "nginx": nginx_status()})
                return
            if self.path.startswith("/api/purge"):
                purge_cache()
                self.send_json(200, {"ok": True, "message": "Cache purged"})
                return
            if self.path.startswith("/api/probe"):
                payload = self.read_json()
                self.send_json(200, {"ok": True, "probe": probe_cdn(payload.get("path", "/index.html"))})
                return
            self.send_error(404)
        except Exception as exc:
            self.send_json(400, {"ok": False, "error": str(exc)})


def main():
    config = load_config()
    port = int(os.environ.get("CDN_LAB_ADMIN_PORT", config.get("admin_port", 8080)))
    server = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    print(f"CDN Lab admin listening on 0.0.0.0:{port}")
    server.serve_forever()


if __name__ == "__main__":
    main()
