# /etc/filebeat/filebeat.yml
filebeat.inputs:
- type: log
  id: my-filestream-id
  enabled: true
  paths:
    - /var/log/nginx/flask_app_access.log
  # Multiline 설정: 새 JSON 객체는 '{' 로 시작한다고 가정
  multiline.pattern: '^\{'
  multiline.negate: true
  multiline.match: after

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

output.logstash:
  hosts: ["127.0.0.1:5044","127.0.0.1:5045"]

processors:
  # 오직 지정된 엔드포인트만 통과시키고 나머지는 drop
  - drop_event:
      when.not:
        regexp:
          request: "^(POST /add_user|POST /delete_user|POST /login|GET /categories|GET /products|GET /category(\\?.+)?|POST /cart/add|GET /cart/view|POST /cart/remove|POST /checkout|GET /checkout_history|POST /add_review|GET /push-subscription|GET /push-messages|GET /search|GET /error)$"
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
