# /etc/filebeat/filebeat.yml
filebeat.inputs:
- type: log
  id: my-filestream-id
  enabled: true
  paths:
    - /var/log/nginx/flask_app_access.log

  # Multiline 설정: 새 JSON 객체는 '{' 로 시작한다고 가정
  multiline.pattern: '^\{'
  multiline.negate: true
  multiline.match: after

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

output.logstash:
  hosts: ["127.0.0.1:5044", "127.0.0.1:5045"]

processors:
  - drop_event:
      when.not:
        regexp:
          # 특정 엔드포인트 (이 예시에서는 7가지만) + HTTP 버전이 1.0 또는 1.1
          # 허용하지 않은 것은 모두 drop.
          request: "^(POST /add_user HTTP/1\\.[01]|GET /categories HTTP/1\\.[01]|GET /products HTTP/1\\.[01]|POST /login HTTP/1\\.[01]|POST /cart/add HTTP/1\\.[01]|POST /delete_user HTTP/1\\.[01]|GET /error HTTP/1\\.[01])$"

  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
