# /etc/filebeat/filebeat.yml
filebeat.inputs:
- type: log
  id: my-filestream-id
  enabled: true
  paths:
    - /var/log/nginx/flask_app_access.log
  # Multiline 설정: 새 JSON 객체는 '{' 로 시작한다고 가정
  multiline.pattern: '^\{'
  multiline.negate: true
  multiline.match: after

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

output.logstash:
  hosts: ["127.0.0.1:5044","127.0.0.1:5045"]

processors:
  - drop_event:
      when:
        or:
          - equals:
              request: "GET /.env.testing HTTP/1.1"
          - and:
              - equals:
                  request: "GET / HTTP/1.1"
              - not:
                  contains:
                    http_user_agent: "python-requests/2.25.1"
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
