# /etc/filebeat/filebeat.yml
filebeat.inputs:
- type: log
  id: my-filestream-id
  enabled: true
  paths:
    - /var/log/nginx/flask_app_access.log
  multiline.pattern: '^\{'
  multiline.negate: true
  multiline.match: after

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

output.logstash:
  hosts: ["127.0.0.1:5044","127.0.0.1:5045"]

processors:
  # 허용된 엔드포인트가 아닌 경우 drop
  - drop_event:
      when.not:
        regexp:
          request: "^(POST /add_user HTTP/1\\.[01]|GET /categories HTTP/1\\.[01]|GET /products HTTP/1\\.[01]|POST /login HTTP/1\\.[01]|POST /cart/add HTTP/1\\.[01]|POST /delete_user HTTP/1\\.[01]|GET /error HTTP/1\\.[01])$"
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
