apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: gender-logistic-random
  namespace: kbm-u-kubeflow-tutorial
spec:
  maxTrialCount: 40
  parallelTrialCount: 4
  maxFailedTrialCount: 4
  resumePolicy: Never
  objective:
    type: maximize
    goal: 0.90
    objectiveMetricName: Valid-macroF1
    additionalMetricNames: [Valid-accuracy, PR-AUC]
  algorithm:
    algorithmName: random
  parameters:
    - { name: min_prelogin_events, parameterType: int,      feasibleSpace: { min: "2", max: "5", step: "1" } }
    - { name: penalty,             parameterType: categorical, feasibleSpace: { list: ["l1","l2","elasticnet"] } }
    - { name: C,                   parameterType: double,   feasibleSpace: { min: "0.1", max: "5.0", step: "0.1" } }
    - { name: l1_ratio,            parameterType: double,   feasibleSpace: { min: "0.2", max: "0.8", step: "0.1" } }
    - { name: scaler,              parameterType: categorical, feasibleSpace: { list: ["standard","robust"] } }
    - { name: class_weight,        parameterType: categorical, feasibleSpace: { list: ["balanced","none"] } }
    - { name: calib_method,        parameterType: categorical, feasibleSpace: { list: ["isotonic","sigmoid"] } }
    - { name: calib_cv,            parameterType: int,      feasibleSpace: { min: "3", max: "5", step: "1" } }
    - { name: threshold_strategy,  parameterType: categorical, feasibleSpace: { list: ["prod","tuned"] } }
    - { name: prod_threshold,      parameterType: double,   feasibleSpace: { min: "0.30", max: "0.60", step: "0.02" } }
    - { name: tune_t_lo,           parameterType: double,   feasibleSpace: { min: "0.20", max: "0.50", step: "0.05" } }
    - { name: tune_t_hi,           parameterType: double,   feasibleSpace: { min: "0.50", max: "0.90", step: "0.05" } }
    - { name: tune_t_steps,        parameterType: int,      feasibleSpace: { min: "61", max: "121", step: "20" } }
  metricsCollectorSpec:
    collector: { kind: StdOut }
  trialTemplate:
    retain : true
    primaryContainerName: training-container
    trialParameters:
      - { name: min_prelogin_events, reference: min_prelogin_events }
      - { name: penalty,             reference: penalty }
      - { name: C,                   reference: C }
      - { name: l1_ratio,            reference: l1_ratio }
      - { name: scaler,              reference: scaler }
      - { name: class_weight,        reference: class_weight }
      - { name: calib_method,        reference: calib_method }
      - { name: calib_cv,            reference: calib_cv }
      - { name: threshold_strategy,  reference: threshold_strategy }
      - { name: prod_threshold,      reference: prod_threshold }
      - { name: tune_t_lo,           reference: tune_t_lo }
      - { name: tune_t_hi,           reference: tune_t_hi }
      - { name: tune_t_steps,        reference: tune_t_steps }
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        backoffLimit: 0               
        ttlSecondsAfterFinished: 600
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            restartPolicy: Never
            containers:
            - name: training-container
              image: mlops.kr-central-2.kcr.dev/kc-kubeflow-registry/jupyter-tensorflow-cuda-full:v1.10.0.py311.1a
              command: ["python","-u","/home/jovyan/gender_train.py"]
              args:
                - --input-path
                - /home/jovyan/datasets/gender/processed_user_behavior.joined.csv
                - --min-prelogin-events
                - ${trialParameters.min_prelogin_events}
                - --penalty
                - ${trialParameters.penalty}
                - --C
                - ${trialParameters.C}
                - --l1-ratio
                - ${trialParameters.l1_ratio}
                - --scaler
                - ${trialParameters.scaler}
                - --class-weight
                - ${trialParameters.class_weight}
                - --calib-method
                - ${trialParameters.calib_method}
                - --calib-cv
                - ${trialParameters.calib_cv}
                - --threshold-strategy
                - ${trialParameters.threshold_strategy}
                - --prod-threshold
                - ${trialParameters.prod_threshold}
                - --tune-t-lo
                - ${trialParameters.tune_t_lo}
                - --tune-t-hi
                - ${trialParameters.tune_t_hi}
                - --tune-t-steps
                - ${trialParameters.tune_t_steps}
                - --artifacts-dir
                - /home/jovyan/models/gender
              volumeMounts:
                - name: workspace
                  mountPath: /home/jovyan
            volumes:
              - name: workspace
                persistentVolumeClaim:
                  claimName: cpu-notebook-workspace
