apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  WELCOME_MESSAGE: "{{ .Values.configMap.WELCOME_MESSAGE }}"
  BACKGROUND_COLOR: "{{ .Values.configMap.BACKGROUND_COLOR }}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-script
data:
  script.sql: |
{{ .Files.Get "files/sql/script.sql" | indent 4 }}

