apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  DB1_PORT: "{{ .Values.secret.DB1_PORT | b64enc }}"
  DB1_URL: "{{ .Values.secret.DB1_URL | b64enc }}"
  DB1_ID: "{{ .Values.secret.DB1_ID | b64enc }}"
  DB1_PW: "{{ .Values.secret.DB1_PW | b64enc }}"
  DB2_PORT: "{{ .Values.secret.DB2_PORT | b64enc }}"
  DB2_URL: "{{ .Values.secret.DB2_URL | b64enc }}"
  DB2_ID: "{{ .Values.secret.DB2_ID | b64enc }}"
  DB2_PW: "{{ .Values.secret.DB2_PW | b64enc }}"
