apiVersion: v1
clusters:
- cluster:
  certificate-authority-data: "${AUTH_DATA}"
  server: ${API_SERVER}
name: kakao-k8s-cluster
contexts:
- context:
  cluster: kakao-k8s-cluster
  user: kakao-k8s-cluster-admin
name: kakao-k8s-cluster-admin@kakao-k8s-cluster
current-context: kakao-k8s-cluster-admin@kakao-k8s-cluster
kind: Config
preferences: {}
users:
- name: kakao-k8s-cluster-admin
user:
  exec:
    apiVersion: client.authentication.k8s.io/v1beta1
    args: null
    command: kic-iam-auth
    env:
    - name: "OS_AUTH_URL"
      value: "https://iam.kakaoi.io/identity/v3"
    - name: "OS_AUTH_TYPE"
      value: "v3applicationcredential"
    - name: "OS_APPLICATION_CREDENTIAL_ID"
      value: "${ACC_KEY}"
    - name: "OS_APPLICATION_CREDENTIAL_SECRET"
      value: "${SEC_KEY}"
    - name: "OS_REGION_NAME"
      value: "kr-central-2"