apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB1_PORT: 'MzMwNg=='
  DB1_URL: "${DB_EP1}"
  DB1_ID: 'YWRtaW4='
  DB1_PW: 'YWRtaW4xMjM0'
  DB2_PORT: 'MzMwNw=='
  DB2_URL: "${DB_EP2}"
  DB2_ID: 'YWRtaW4='
  DB2_PW: 'YWRtaW4xMjM0'
